// Generated by josh-approved-factory/scripts/generate-credits.mjs.
// Source: credits-config.json + package.json + node_modules.
// Do not edit by hand — re-run the generator after dep updates.

export interface CreditEntry {
  name: string;
  version: string;
  license: string;
  url: string;
}

export const CREDITS_INTRO = "This app is built on the work of these open-source projects.";

export const CREDITS: CreditEntry[] = [
  {
    "name": "React Native",
    "version": "0.85.3",
    "license": "MIT",
    "url": "https://reactnative.dev/"
  },
  {
    "name": "Expo",
    "version": "56.0.11",
    "license": "MIT",
    "url": "https://github.com/expo/expo/tree/main/packages/expo"
  },
  {
    "name": "React Navigation",
    "version": "7.3.1",
    "license": "MIT",
    "url": "https://reactnavigation.org"
  },
  {
    "name": "react-native-svg",
    "version": "15.15.4",
    "license": "MIT",
    "url": "https://github.com/react-native-community/react-native-svg"
  },
  {
    "name": "Zustand",
    "version": "5.0.14",
    "license": "MIT",
    "url": "https://github.com/pmndrs/zustand"
  },
  {
    "name": "Lucide",
    "version": "1.17.0",
    "license": "ISC",
    "url": "https://lucide.dev"
  },
  {
    "name": "IBM Plex",
    "version": "",
    "license": "OFL 1.1",
    "url": "https://www.ibm.com/plex/"
  }
];
